-- ============================================================================
-- ЗАДАНИЕ ФИНАЛ: Создать таблицу readers
-- ============================================================================

CREATE TABLE readers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE reader_books (
    reader_id BIGINT NOT NULL REFERENCES readers(id),
    book_id   BIGINT NOT NULL REFERENCES books(id),
    PRIMARY KEY (reader_id, book_id)
);

CREATE INDEX idx_reader_books_reader ON reader_books(reader_id);
CREATE INDEX idx_reader_books_book   ON reader_books(book_id);
